version: '3.8'

services:
  productos-db:
    image: postgres:17
    container_name: productos_database
    environment:
      POSTGRES_USER: ecovida
      POSTGRES_PASSWORD: ecovida
      POSTGRES_DB: productosdb
    ports:
      - "5528:5432"
    volumes:
      - ./backuppg:/var/lib/postgresql/data

volumes:
  backuppg:
