version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: auth-ecovida
    restart: always
    ports:
      - "27049:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mspadron 
      MONGO_INITDB_ROOT_PASSWORD: admin2828 
      MONGO_INITDB_DATABASE: EcovidaAuthDB 
    volumes:
      - mongo-data:/data/db 

volumes:
  mongo-data:
